apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidfort_assesment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rapidfort_assesment
  template:
    metadata:
      labels:
        app: rapidfort_assesment
    spec:
       containers:
        - name: rapidfort_assesment
          image: docker.io/1amithrx/chatbot:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rapidfort_assesment-service
spec:
  selector:
    app: rapidfort_assesment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer