apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidfort_assesment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rapidfort_assesment
  template:
    metadata:
      labels:
        app: rapidfort_assesment
    spec:
       containers:
        - name: rapidfort_assesment
          image: docker.io/1amithrx/chatbot:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"   
              cpu: "100m"      
            limits:
              memory: "128Mi"  
              cpu: "200m"      